-- docs/schema.sql
-- Mastermind: schema + seed (PostgreSQL 12+ for generated columns)

-- =======================
-- SCHEMA
-- =======================

CREATE TABLE IF NOT EXISTS users (
    id              SERIAL PRIMARY KEY,
    username        VARCHAR(50) NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS games (
    id               SERIAL PRIMARY KEY,
    user_id          INTEGER REFERENCES users(id) ON DELETE SET NULL,

    secret_code      CHAR(4) NOT NULL CHECK (secret_code ~ '^[0-7]{4}$'),

    status           TEXT NOT NULL CHECK (status IN ('active','won','lost')) DEFAULT 'active',
    difficulty       TEXT NOT NULL CHECK (difficulty IN ('easy','medium','hard')) DEFAULT 'medium',

    max_guesses      INTEGER NOT NULL DEFAULT 10 CHECK (max_guesses > 0),
    attempts_used    INTEGER NOT NULL DEFAULT 0 CHECK (attempts_used BETWEEN 0 AND max_guesses),

    guesses_left     INTEGER GENERATED ALWAYS AS (max_guesses - attempts_used) STORED,

    started_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at       TIMESTAMPTZ,
    timer_total_s    INTEGER CHECK (timer_total_s IS NULL OR timer_total_s > 0),

    score            INTEGER,
    player_username  VARCHAR(80)
);

CREATE INDEX IF NOT EXISTS idx_games_user_id ON games(user_id);

CREATE TABLE IF NOT EXISTS guesses (
    id              SERIAL PRIMARY KEY,
    game_id         INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,

    digits          CHAR(4) NOT NULL CHECK (digits ~ '^[0-7]{4}$'),
    exact_guess     SMALLINT NOT NULL CHECK (exact_guess BETWEEN 0 AND 4),
    number_only     SMALLINT NOT NULL CHECK (number_only BETWEEN 0 AND 4),

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_guesses_game_id ON guesses(game_id);

-- =======================
-- SEED (development only)
-- =======================

TRUNCATE TABLE guesses RESTART IDENTITY CASCADE;
TRUNCATE TABLE games   RESTART IDENTITY CASCADE;
TRUNCATE TABLE users   RESTART IDENTITY CASCADE;

INSERT INTO users (username, password_hash)
VALUES ('olga', '$2b$12$Hoa4bBzRGRvbqHizEePhne8p3OuaOzPCHo.MyM9GLTplpyYwzVXOa');

-- Demo game: code "0135", 3-minute timer, medium difficulty
-- guesses_left is generated by the DB (10 - 0 = 10 initially)
INSERT INTO games (user_id, secret_code, status, difficulty, max_guesses, attempts_used, timer_total_s, player_username)
VALUES (1, '0135', 'active', 'medium', 10, 0, 180, 'olga');

-- Guesses for game id 1 (for secret '0135')
-- '2246' -> 0 exact, 0 present
-- '0123' -> 2 exact ('0','1'), 1 present ('3')
INSERT INTO guesses (game_id, digits, exact_guess, number_only) VALUES
  (1, '2246', 0, 0),
  (1, '0123', 2, 1);
